# Question:
    # My friend John and I are members of the "Fat to Fit Club (FFC)". John is worried because each month a list with the weights of members is published and each month he is the last on the list which means he is the heaviest.
    # I am the one who establishes the list so I told him: "Don't worry any more, I will modify the order of the list". It was decided to attribute a "weight" to numbers. The weight of a number will be from now on the sum of its digits.
    # For example 99 will have "weight" 18, 100 will have "weight" 1 so in the list 100 will come before 99. Given a string with the weights of FFC members in normal order can you give this string ordered by "weights" of these numbers?

# Example:
    # "56 65 74 100 99 68 86 180 90" ordered by numbers weights becomes: "100 180 90 56 65 74 68 86 99"
    # When two numbers have the same "weight", let us class them as if they were strings and not numbers: 100 is before 180 because its "weight" (1) is less than the one of 180 (9) and 180 is before 90 since, having the same "weight" (9), it comes before as a string.
    # All numbers in the list are positive numbers and the list can be empty.
  
# Note: 
    # it may happen that the input string have leading, trailing whitespaces and more than a unique whitespace between two consecutive numbers
    # Don't modify the input
    # For C: The result is freed.


# My answer:
def order_weight(string)
    weight = string.split                                                    #convert string into an array of numbers
    new_weight = weight.map {|x| x.to_i.digits.sum}                          #calculate the new weight
    weight_hash = Hash[weight.zip new_weight]                                #create a hash with key-value pair (weight => new weight)
    p order = weight_hash.sort_by {|key, value| value}.to_h.keys.join(" ")   #sort the hash with its values
end                                                                          #return its keys in order as a string

order_weight("56 65 74 100 99 68 86 180 90") #"100 180 90 56 65 74 68 86 99"
order_weight("103 123 4444 99 2000") #"2000 103 123 4444 99"
order_weight("2000 10003 1234000 44444444 9999 11 11 22 123") #"11 11 2000 10003 22 123 1234000 44444444 9999": I didn't pass this test

# Issues:
    # Can't pass test 3 as I'm not able to produce a hash with the same key with different values
    # (i.e. as long as there's no duplicate value in the original string, my code would work fine)

# Methods used in my answer:
    # .split [string -> array]: Divides str into substrings based on a delimiter, returning an array of these substrings.
    # .map [array]: Invokes the given block once for each element of self.
    # .digits [integer -> array]: Returns the digits of int's place-value representation with radix base (default: 10). The digits are returned as an array with the least significant digit as the first array element.
    # .sum [array]: Returns the sum of elements. 
    # .zip: Takes one element from enum and merges corresponding elements from each args. 
    # .sort_by: Sorts enum using a set of keys generated by mapping the values in enum through the given block.
    # .join [array -> string]: Returns a string created by converting each element of the array to a string, separated by the given separator. 
